### ISSUE TITLE
Frozen Breakouts doesn't work

### ISSUE THREAD

**Issue by Coeur** [city41/breakouts#76] opened 2015-03-24 07:25 UTC
I've tried Chrome 41, Internet Explorer 11 and Firefox 37.
I've tried all implementations, including ClojureScript/React.
Everything is working but Frozen implementation (can't start the game).

**Comment by city41** [comment] 2015-03-24 15:03
Yup, looks like something happened to it. Thanks for the heads up, I'm looking into it now.

**Comment by city41** [comment] 2015-03-24 15:20
Hey @phated, it looks like AudioBufferSourceNode no longer has `noteOn()`, which looks to be the root cause here. Any plans to update Frozen? Looks like `start()` is the way to go, but as far as I can tel start lacks the ability to specify the starting point. I'm not that familiar with the web audio api.

**Comment by city41** [comment] 2015-03-24 15:22
Ope I'm wrong, looks like start() does allow specifying a start time: https://developer.mozilla.org/en-US/docs/Web/API/Web_Audio_API/Porting_webkitAudioContext_code_to_standards_based_AudioContext

**Comment by city41** [comment] 2015-03-24 15:27
I did a temporary patch to get the deployed version of Frozen working again:

* `s/noteOn/start/g` for all of dist/game.js
* `s/createGainNode/createGain/g` for all of dist/game.js

@Coeur you should find The [Frozen Breakout](http://www.jsbreakouts.org/frozen/index.html) works again. Let me know if it still doesn't (may need to clear cache).

@phated looks like just some minor method name changes are needed for Frozen

**Comment by phated** [comment] 2015-03-24 17:49
@city41 we actually had this fixed in our unreleased 0.5.0 branch.  Let me review it and see if we can get it updated

**Closed** 2016-03-29 10:42 UTC
